name: validate
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]
jobs:
  unittest:
    name: unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: install container setup modules
        run: |
          pip install requests
        working-directory: backend/app
      - name: Setup docker container
        run: |
          docker-compose up -d
        working-directory: backend/app
      - name: wait build container
        run: |
          python3 wait_neo4j_container.py
        working-directory: .github/workflows/script
      - name: install modules
        run: |
          pip install -r requirements.txt
        working-directory: backend/app
      - name: Generate Report
        run: |
          pytest -v --cov=. --cov-report xml:xunit-result-0.xml
          sed -i -e 's/filename=\"/filename=\"backend\/app\//g' xunit-result-0.xml
        working-directory: backend/app
